yarn add -D @icona/generator

name: Build

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Replace with the desired Node.js version

      - name: Install dependencies
        run: yarn install  # Replace with the command to install dependencies (e.g., npm install)

      - name: Run build script
        run: node icona.js  # Replace with the command to run your build script
